.TL
Welcome to my Blog
.PP
This blog is a hand coded monstrosity that turns Groff pages into blog posts.
It's a work in progress, but I'm happy with it so far.

This blog is about things that interest me. This will range from technical
topics to personal projects and anything in between.

DISCLAIMER: I might offend you. I have opinions and I'm not afraid to share them.
I'm not responsible for any hurt feelings, especially not yours. If you don't like
it, don't read it.
.SH
Blog entries:
.PP

